config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'suits#index'
  resources :suits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent, class_name: :Category  
  has_many :children, class_name: :Category, foreign_key: :parent_id  
end

app/models/suit.rb
class Suit < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user 

  # enum maxtemperature:{'--': 0,'10': 1, '15': 2, '20': 3, '25': 4, '30': 5, '35': 6, '40': 7}
  # enum minitemperature:{'--': 0,'0': 1, '10': 2, '15': 3, '20': 4, '25': 5}, _suffix: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :suits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/suits_controller.rb
class SuitsController < ApplicationController

  before_action :authenticate_user!

  def index
    @all_categories = Category.all
    mini_temp = params[:mini_temp]
    max_temp = params[:max_temp]
    mini_temp = mini_temp.to_s
    max_temp = max_temp.to_s
    if params[:status] == "2"
      @suits = Suit.where('minitemperature <=?', mini_temp).where('maxtemperature >=?', max_temp).where(user_id: current_user.id)
    else
      @suits = Suit.where('minitemperature <=?', mini_temp).where('maxtemperature >=?', max_temp).where("(status = ?) OR (status = ?)", 1, 3).where(user_id: current_user.id)
    end
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @suit = Suit.new
    @categories = Category.order("id ASC").limit(4)
    @all_categories = Category.all
  end

  def show
    @suit = Suit.find(params[:id])
  end

  def create
    @suit= Suit.new( image: suit_params[:image], status: suit_params[:status], minitemperature: suit_params[:minitemperature], maxtemperature: suit_params[:maxtemperature], category_id: suit_params[:category_id], user_id: current_user.id)
    num = suit_params[:category_id]


    num = num.to_i
    chidlren_category = Category.find(num)
    id = chidlren_category.parent_id
    suit_category = Category.find(id)

    tops = {num:1, name:"tops"}
    thick_tops = {num:2, name:"thick_tops"}
    outer = {num:3, name:"outer"}
    pants = {num:4, name:"pants"}

    category_array = [tops,thick_tops,outer,pants]
    category_array.each do |category|
      case suit_category.id
      when category[:num]
      @suit.name = category[:name]
      end
    end


    @outers = Category.where(parent_id: 3)
    @outers.each do |outer|
      if outer.id == num.to_i
        @suit.status = 3
      end
    end
    
    @suit.save 
    redirect_to root_path, notice: 'グループを作成しました'
  end

  private

  def suit_params
    params.require(:suit).permit(:image, :status, :minitemperature, :maxtemperature, :category_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  def create
    super
  end
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clothes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script defer src="https://use.fontawesome.com/releases/v5.5.0/js/all.js" integrity="sha384-GqVMZRt5Gn7tB9D9q7ONtcp4gtHIUEW/yG7h98J7IpE3kpi+srfFyyB/04OV6pG0" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/suits/index.html.erb
<div class = "top">
  <div class = inner>
    <div class = "side-bar">
      <div class = "side-bar__header">
        <% if user_signed_in? %>
          <%= link_to "ログアウト",  destroy_user_session_path, method: :delete, class: "side-bar__header__logout" %>
          <%= link_to "服を登録", new_suit_path, data: {"turbolinks" => false}, class: "side-bar__header__cloth" %>
        <% else %>
          <%# 現在不要 %>
          <%= link_to "新規登録", new_user_registration_path, class: 'side-bar__header__singin' %>
          <%= link_to "ログイン", new_user_session_path, class: 'side-bar__header__singin' %>         
        <%end%>
      </div>
      <div class ="weather-list">
      </div>
    </div>


<div class= "content">
  <div class = "content__inner">
    <div class = "content__inner__outer"></div>
    <div class = "content__inner__thick_tops"></div>
    <div class = "content__inner__tops"></div>
    <div class = "content__inner__pants"></div>
  </div>
</div>

<div id="all_category" data-categories="<%= @all_categories.to_json %>"></div> 
</div>
</div>

app/views/suits/new.html.erb
<div class = "registar-content">
  <div class = "registar-content__inner">
    <%= form_with model: @suit do |form| %>
      <div class="registar-content__inner__image" onClick="$('#suit_img').click()">
        <%= form.label "picture",class:"registar-content__inner__image__label" %>
        <i class="fas fa-tshirt"></i>
        <p class="registar-content__inner__image__label__guide"> Click Me! </p>
      </div>
      <%= form.file_field :image, style: "display:none;", id: :suit_img %>
        <div class = "registar-content__inner__form">
          <div class = "registar-content__inner__form__category">
            <%= form.label "Category",class:"registar-content__inner__form__category__label" %>
            <div class = "registar-content__inner__form__category__first">
              <%= form.collection_select :category_id, @categories, :id, :name, :prompt => "--" %>
            </div>
          </div>
          <div class = "registar-content__inner__form__status">
            <%= form.label "Status",class:"registar-content__inner__form__status__label" %>
            <div class = "registar-content__inner__form__status__box">
              <div class = "registar-content__inner__form__status__box__temperature">
                <p class = "registar-content__inner__form__status__box__temperature__question">何度ぐらいで使用しますか？</p>
                <div class = "registar-content__inner__form__status__box__temperature__select ">
                  <div class = "registar-content__inner__form__status__box__temperature__select__mini">
                    <%= form.select :minitemperature, [["--",0],[0,1],[5,2],[10,3],[15,4],[20,5],[25,6],[30,7],[35,8]], {}, {id: 'minitemperature'} %>
                  </div>
                  <p class = "registar-content__inner__form__status__box__temperature__select__degree max">〜</p>
                  <div class = "registar-content__inner__form__status__box__temperature__select__max">
                    <%= form.select :maxtemperature, [["--",0],[5,1], [10,2],[15,3],[20,4],[25,5],[30,6],[35,7],[40,8]], {}, {id: 'maxtemperature'}%>
                  </div>
                  <p class = "registar-content__inner__form__status__box__temperature__select__degree">℃</p>
                </div>
              </div>
              <div class = "registar-content__inner__form__status__box__washing" id = "washing">
                <p class = "registar-content__inner__form__status__box__washing__question">タンブラー乾燥は可能ですか？</p>
                <div class = "registar-content__inner__form__status__box__washing__anwser">
                  <%= form.radio_button :status, "1", id: "yes" %>
                  <%= form.label "yes", for: "yes", id: "yes" %>
                  <%= form.radio_button :status, "2", id: "no" %>
                  <%= form.label "no", for: "no", id: "yes"  %>
                </div>
              </div>              
            </div>
          </div>
        <div class = "registar-content__inner__form__finish">
          <%= form.submit 'SENT!', class: "registar-content__inner__form__finish__submit"%>
        </div>
      </div>
    <%end%>
  </div>
  <div id="all_category" data-categories="<%= @all_categories.to_json %>"></div> 

app/views/suits/show.html.erb
<%= @suit.id %>
<%= @suit.name %>
<%= @suit.maxtemperature %>
<%# <% if @suit.maxtemperature = 1%>
<%# <div class = "maxtemperature" >max 5</div> %>
<%# <% elsif @suit.maxtemperature = 2 %> 
<%# <div class = "maxtemperature" >max 10</div> %>
<%# <% end %>
<%# <%= @suit.minitemperature %> 
<%# <%= @suit.category_id %> 

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>